//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspenlaub.Net.GitHub.CSharp.VishizhukelNetWeb.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspenlaub.Net.GitHub.CSharp.VishizhukelNetWeb.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always fails.
        /// </summary>
        internal static string AlwaysFails {
            get {
                return ResourceManager.GetString("AlwaysFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always succeeds.
        /// </summary>
        internal static string AlwaysSucceeds {
            get {
                return ResourceManager.GetString("AlwaysSucceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can find anchor.
        /// </summary>
        internal static string CanFindAnchor {
            get {
                return ResourceManager.GetString("CanFindAnchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can find body.
        /// </summary>
        internal static string CanFindBody {
            get {
                return ResourceManager.GetString("CanFindBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can find exactly one input element.
        /// </summary>
        internal static string CanFindExactlyOneInputElement {
            get {
                return ResourceManager.GetString("CanFindExactlyOneInputElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can find Lamas&apos; main by class.
        /// </summary>
        internal static string CanFindLamasMainByClass {
            get {
                return ResourceManager.GetString("CanFindLamasMainByClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find anchor (because it is not div-like).
        /// </summary>
        internal static string CannotFindAnchorWhichIsNotDivLike {
            get {
                return ResourceManager.GetString("CannotFindAnchorWhichIsNotDivLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find exactly one input element.
        /// </summary>
        internal static string CannotFindExactlyOneInputElement {
            get {
                return ResourceManager.GetString("CannotFindExactlyOneInputElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test cases can only be run using real web view.
        /// </summary>
        internal static string CanOnlyRunTestCasesWithRealWebView {
            get {
                return ResourceManager.GetString("CanOnlyRunTestCasesWithRealWebView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No result received.
        /// </summary>
        internal static string NoResultReceived {
            get {
                return ResourceManager.GetString("NoResultReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result is inconclusive.
        /// </summary>
        internal static string ResultIsInconclusive {
            get {
                return ResourceManager.GetString("ResultIsInconclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script call failed as expected, but not with error message &quot;{0}&quot;.
        /// </summary>
        internal static string ScriptCallFailedButWrongErrorMessage {
            get {
                return ResourceManager.GetString("ScriptCallFailedButWrongErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script call failed technically.
        /// </summary>
        internal static string ScriptCallFailedTechnically {
            get {
                return ResourceManager.GetString("ScriptCallFailedTechnically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script call succeeded, expected failure with error message &quot;{0}&quot;.
        /// </summary>
        internal static string ScriptCallFailureExpected {
            get {
                return ResourceManager.GetString("ScriptCallFailureExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script call succeeded, but dom element does not have class &quot;{0}&quot;.
        /// </summary>
        internal static string ScriptCallSucceededButDomElementDoesNotHaveClass {
            get {
                return ResourceManager.GetString("ScriptCallSucceededButDomElementDoesNotHaveClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script call succeeded, but there is a mismatch in NthOfClass.
        /// </summary>
        internal static string ScriptCallSucceededButMisMatchInNthOfClass {
            get {
                return ResourceManager.GetString("ScriptCallSucceededButMisMatchInNthOfClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script call succeeded, but no dom element with classes was returned.
        /// </summary>
        internal static string ScriptCallSucceededButNoDomElement {
            get {
                return ResourceManager.GetString("ScriptCallSucceededButNoDomElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script call succeeded, but dom element does not have NthOfClass.
        /// </summary>
        internal static string ScriptCallSucceededButNoNthOfClass {
            get {
                return ResourceManager.GetString("ScriptCallSucceededButNoNthOfClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test case failed.
        /// </summary>
        internal static string TestCaseFailed {
            get {
                return ResourceManager.GetString("TestCaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test case succeeded.
        /// </summary>
        internal static string TestCaseSucceeded {
            get {
                return ResourceManager.GetString("TestCaseSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web View Window.
        /// </summary>
        internal static string WebViewWindowTitle {
            get {
                return ResourceManager.GetString("WebViewWindowTitle", resourceCulture);
            }
        }
    }
}
