//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspenlaub.Net.GitHub.CSharp.VishizhukelNetWeb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspenlaub.Net.GitHub.CSharp.VishizhukelNetWeb.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App failed.
        /// </summary>
        internal static string AppFailed {
            get {
                return ResourceManager.GetString("AppFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deserialize oucid response.
        /// </summary>
        internal static string CouldNotDeserializeOucidResponse {
            get {
                return ResourceManager.GetString("CouldNotDeserializeOucidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deserialize script call JSON result.
        /// </summary>
        internal static string CouldNotDeserializeScriptCallJsonResult {
            get {
                return ResourceManager.GetString("CouldNotDeserializeScriptCallJsonResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load URL.
        /// </summary>
        internal static string CouldNotLoadUrl {
            get {
                return ResourceManager.GetString("CouldNotLoadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing script.
        /// </summary>
        internal static string ExecutingScript {
            get {
                return ResourceManager.GetString("ExecutingScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigating again.
        /// </summary>
        internal static string NavigatingAgain {
            get {
                return ResourceManager.GetString("NavigatingAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigating to URL &apos;{0}&apos; and wait for start of navigation.
        /// </summary>
        internal static string NavigatingToUrl {
            get {
                return ResourceManager.GetString("NavigatingToUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No script statement was provided.
        /// </summary>
        internal static string NoScriptStatementProvided {
            get {
                return ResourceManager.GetString("NoScriptStatementProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still not navigating after {0} second/-s.
        /// </summary>
        internal static string NotNavigatingAfterSeconds {
            get {
                return ResourceManager.GetString("NotNavigatingAfterSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not navigating anymore.
        /// </summary>
        internal static string NotNavigatingAnymore {
            get {
                return ResourceManager.GetString("NotNavigatingAnymore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oucid already is present in the URL, this should not happen.
        /// </summary>
        internal static string OucidAlreadyPresentInUrl {
            get {
                return ResourceManager.GetString("OucidAlreadyPresentInUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while waiting for potential end of navigation.
        /// </summary>
        internal static string ProblemWaitingForPotentialNavigationEnd {
            get {
                return ResourceManager.GetString("ProblemWaitingForPotentialNavigationEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset model URL and sync.
        /// </summary>
        internal static string ResetModelUrlAndSync {
            get {
                return ResourceManager.GetString("ResetModelUrlAndSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script call failed.
        /// </summary>
        internal static string ScriptCallFailed {
            get {
                return ResourceManager.GetString("ScriptCallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script call failure expected.
        /// </summary>
        internal static string ScriptCallFailureExpected {
            get {
                return ResourceManager.GetString("ScriptCallFailureExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script call JSON result is null or empty.
        /// </summary>
        internal static string ScriptCallJsonResultIsEmpty {
            get {
                return ResourceManager.GetString("ScriptCallJsonResultIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script executed, deserializing result.
        /// </summary>
        internal static string ScriptExecutedDeserializingResult {
            get {
                return ResourceManager.GetString("ScriptExecutedDeserializingResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set model URL and sync.
        /// </summary>
        internal static string SetModelUrlAndAsync {
            get {
                return ResourceManager.GetString("SetModelUrlAndAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User interface does not contain a WebView.
        /// </summary>
        internal static string UiDoesNotContainAWebView {
            get {
                return ResourceManager.GetString("UiDoesNotContainAWebView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation takes longer, waiting until not navigating anymore.
        /// </summary>
        internal static string WaitLongerUntilNotNavigatingAnymore {
            get {
                return ResourceManager.GetString("WaitLongerUntilNotNavigatingAnymore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait until not navigating anymore.
        /// </summary>
        internal static string WaitUntilNotNavigatingAnymore {
            get {
                return ResourceManager.GetString("WaitUntilNotNavigatingAnymore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web view must be wired before this method can be used.
        /// </summary>
        internal static string WebViewMustBeWired {
            get {
                return ResourceManager.GetString("WebViewMustBeWired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web view still is busy with a preceding request after {0} second/-s.
        /// </summary>
        internal static string WebViewStillBusyAfter {
            get {
                return ResourceManager.GetString("WebViewStillBusyAfter", resourceCulture);
            }
        }
    }
}
